name: README Anime List
description: '自動抓自己的 Bangumi 追番進度到 README 頁面'

inputs:
  target:
    description: 'Target README'
    required: true
  template:
    description: 'README template file'
    required: true
  bangumi_username:
    description: 'The your Bangumi username or uid'
    required: true
  type:
    description: 'Bangumi collection type'
    default: 3
  bangumi_limit:
    description: 'Pull limit for Bangumi list'
    default: 10
  user_agent:
    description: 'User agent for Bangumi API'
    default: 'ycs77/readme-anime-list'

runs:
  using: 'node16'
  main: 'dist/index.js'

branding:
  icon: 'list'
  color: 'red'
